theme: jekyll-theme-minimal
title: Interactive Plotting
description: A simple example to show the interactive plot
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: aaa
    url: /
